title: "2 — VMC"
views:
  - title: "2 — VMC — Plancia"
    path: vmc
    icon: mdi:hvac
    type: sections
    max_columns: 3
    sections:
      - type: grid
        title: "Stato & Comandi"
        cards: []
      - type: grid
        title: "KPI"
        cards: []
      - type: grid
        title: "Trend & Lock"
        cards: []
# Follow logica/regole_plancia2.txt for colors and structure.
